// Package internalhttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package internalhttp

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateEventRequest defines model for CreateEventRequest.
type CreateEventRequest struct {
	Description  *string   `json:"description,omitempty"`
	EndTime      time.Time `json:"end_time"`
	NotifyBefore *int32    `json:"notify_before,omitempty"`
	StartTime    time.Time `json:"start_time"`
	Title        string    `json:"title"`
	UserId       int64     `json:"user_id"`
}

// DeleteResponse defines model for DeleteResponse.
type DeleteResponse struct {
	Message *string `json:"message,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// Event defines model for Event.
type Event struct {
	Description *string    `json:"description,omitempty"`
	EndTime     *time.Time `json:"end_time,omitempty"`
	Id          *int64     `json:"id,omitempty"`

	// NotifyBefore За сколько минут до события отправлять уведомление
	NotifyBefore *int32     `json:"notify_before,omitempty"`
	StartTime    *time.Time `json:"start_time,omitempty"`
	Title        *string    `json:"title,omitempty"`
	UserId       *int64     `json:"user_id,omitempty"`
}

// UpdateEventRequest defines model for UpdateEventRequest.
type UpdateEventRequest struct {
	Description  *string    `json:"description,omitempty"`
	EndTime      *time.Time `json:"end_time,omitempty"`
	NotifyBefore *int32     `json:"notify_before,omitempty"`
	StartTime    *time.Time `json:"start_time,omitempty"`
	Title        *string    `json:"title,omitempty"`
	UserId       *int64     `json:"user_id,omitempty"`
}

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody = CreateEventRequest

// UpdateEventJSONRequestBody defines body for UpdateEvent for application/json ContentType.
type UpdateEventJSONRequestBody = UpdateEventRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Получить все события
	// (GET /api/v1/events)
	GetEvents(w http.ResponseWriter, r *http.Request)
	// Создать новое событие
	// (POST /api/v1/events)
	CreateEvent(w http.ResponseWriter, r *http.Request)
	// Получить события на день
	// (GET /api/v1/events/day/{date})
	GetEventsByDay(w http.ResponseWriter, r *http.Request, date openapi_types.Date)
	// Получить события на месяц
	// (GET /api/v1/events/month/{date})
	GetEventsByMonth(w http.ResponseWriter, r *http.Request, date openapi_types.Date)
	// Получить события на неделю
	// (GET /api/v1/events/week/{date})
	GetEventsByWeek(w http.ResponseWriter, r *http.Request, date openapi_types.Date)
	// Удалить событие
	// (DELETE /api/v1/events/{id})
	DeleteEvent(w http.ResponseWriter, r *http.Request, id int64)
	// Получить событие по ID
	// (GET /api/v1/events/{id})
	GetEvent(w http.ResponseWriter, r *http.Request, id int64)
	// Обновить событие
	// (PUT /api/v1/events/{id})
	UpdateEvent(w http.ResponseWriter, r *http.Request, id int64)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Получить все события
// (GET /api/v1/events)
func (_ Unimplemented) GetEvents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать новое событие
// (POST /api/v1/events)
func (_ Unimplemented) CreateEvent(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить события на день
// (GET /api/v1/events/day/{date})
func (_ Unimplemented) GetEventsByDay(w http.ResponseWriter, r *http.Request, date openapi_types.Date) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить события на месяц
// (GET /api/v1/events/month/{date})
func (_ Unimplemented) GetEventsByMonth(w http.ResponseWriter, r *http.Request, date openapi_types.Date) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить события на неделю
// (GET /api/v1/events/week/{date})
func (_ Unimplemented) GetEventsByWeek(w http.ResponseWriter, r *http.Request, date openapi_types.Date) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Удалить событие
// (DELETE /api/v1/events/{id})
func (_ Unimplemented) DeleteEvent(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить событие по ID
// (GET /api/v1/events/{id})
func (_ Unimplemented) GetEvent(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновить событие
// (PUT /api/v1/events/{id})
func (_ Unimplemented) UpdateEvent(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateEvent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEvent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventsByDay operation middleware
func (siw *ServerInterfaceWrapper) GetEventsByDay(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "date" -------------
	var date openapi_types.Date

	err = runtime.BindStyledParameterWithOptions("simple", "date", chi.URLParam(r, "date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventsByDay(w, r, date)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventsByMonth operation middleware
func (siw *ServerInterfaceWrapper) GetEventsByMonth(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "date" -------------
	var date openapi_types.Date

	err = runtime.BindStyledParameterWithOptions("simple", "date", chi.URLParam(r, "date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventsByMonth(w, r, date)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEventsByWeek operation middleware
func (siw *ServerInterfaceWrapper) GetEventsByWeek(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "date" -------------
	var date openapi_types.Date

	err = runtime.BindStyledParameterWithOptions("simple", "date", chi.URLParam(r, "date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "date"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEventsByWeek(w, r, date)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteEvent operation middleware
func (siw *ServerInterfaceWrapper) DeleteEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEvent operation middleware
func (siw *ServerInterfaceWrapper) GetEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateEvent operation middleware
func (siw *ServerInterfaceWrapper) UpdateEvent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateEvent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/events", wrapper.GetEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/events", wrapper.CreateEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/events/day/{date}", wrapper.GetEventsByDay)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/events/month/{date}", wrapper.GetEventsByMonth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/events/week/{date}", wrapper.GetEventsByWeek)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/events/{id}", wrapper.DeleteEvent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/events/{id}", wrapper.GetEvent)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/events/{id}", wrapper.UpdateEvent)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZb2/T1hf+Ktb9/V66jfsH1vkdULaBhoRYJ9RtFXKT09aQ2Ob6pltWRWpSBEhUq4SQ",
	"9mpMiC9gsmaEtglf4dxvNJ17nTSJneJsXdVMeZM4ie/N+fM8zznneofl/VLge+CJkNk7LMxvQclRlzc4",
	"OAJuboMn7sHjMoSCvoWfnFJQBLosQJjnbiBc32M2w9f4TtbkHv6Jh9jENrawacgafpS72MK2rGPETAZe",
	"4YFwS8BsNm/NX52xFmbmP1uZm7Mty7as75jJPF+4G5UH67Dhc2D23BWThcLhIm2ZdbpMuIKsYvhS1mRd",
	"7mJTPsPIkDUDj7CDJxhhGw+xgx+Yycoh8Adugdlz8wuLV6omC7gfABcuhAnH+lzO6KNXLhaddVogeBlM",
	"JioBLQ4Fd71NVu0PQv/mI+Kx4fOSI5jNCo6AGbUsZcuhqPXtSwHs7eF6YmF+tImuJ2ATOG3YH/NRVlrj",
	"WhknaSCkWfKV2KiXwH5HKZeDvl5dZEnfqibj8Ljscigw+/vYpgGH+zJ0+ldrvZ389YeQF2TGMhRBwD0I",
	"A98LYYgeJQhDZ1P5+AY7+E6+kHUNmD08xAiPFYI6LAG/3sKBOJ25RyJE1RRrb3Lu8xHGAv2W/Bts65cI",
	"P8SIT7E3XnuGtWnbZDOZ1OdCZEepwWVUn7HUJBsNNXE+SZQUVRmK/a/KR+XisdyndwNPVNj3ZN0gh+nn",
	"HhLkgYEdWVe5ibCBx/JA1uU+gbmBTRWfkxjSLWyyc9CtMWXpLJ3JoisJ/H4bFKY1dFpD/4s1dAjr5C7k",
	"y9wVlW+oh9QouA4OB36tLLbo07r69EV389v3V5g5xIDb91cMWccOHhE2SEKOSTUiEhT6RsnIE2zhEUby",
	"KbawNWvgK5IYUhS5T3cZ+B4j/INECTvYoM1sg2zwufuzQ39kG9ow44eyZS3khf8IPHWpGgFlPrNjc0+9",
	"3xIiYFXy1PU2/CR7v1pZuWtcu3ura7WsYVPuYgNbsoYR5aRbsA8xkrvyoI9yN5wieAWH03pmsm3god50",
	"btaatShdfgCeE7jMZguz1uwCM1ngiC0V5ZwTuLntuRxsd9v4TVBCQ4RUDt8qMJt9CeKmvoM6IN0GqLvn",
	"LYve8r4n4nLrBEHRzauluYehprAeDejKFVBSC//PYYPZ7H+50yEiF08QOV26T4HicO5UdPiGRO8tsR+b",
	"8jm25Qv8oGtEA5uyTsuvjGncmTYNdEBptrzUtYu4hG1sywNds55jC99RAk+TSq+Rxn25VHJ4hZb/rirh",
	"nnyGLVXZsEH3DxVBSruzGVLzGWdsjeTTD1Ny1jeEMd23Qiiu+4XKucUkZcyrDvbIJG/VBGTmzi8rGikp",
	"2RjqeSmK71XfG/ehixeKjd+wSboqdxU6jmS9i1eSGypfHVnTVn1+gVa9wohqpraCAEsFdNJ486abWc2a",
	"dqzbg8xRLWGCOVVzSP9yBaeS26EaWv20FF6vLDsVpaXcKYEATpvvjIxxw5BPCAFUW1WpWV1dXZ25c2dm",
	"eZkas5QKT6MF7UFiTU2Do0oLWceGOWb2ZWOgF0iZldYmScIvB037M2fEWHsx8RVmeL5qE0xVYy33s9Gl",
	"5HtiawzC3KH7s1OmjRF1pXhMH06wKWvyQD6dkmlKpgkhUw+z2ej0I8CjMdh0H+DR3yRTW52ZNPEYW1My",
	"Tck0EWTqYVb+ko1OO26hqkftIghIUkkfwXcHpCEapeDbLWRD98iTj3+K77NyNPQ8IcNIlHiUsGgtXiBk",
	"Mj0tmCgUv40DmsRw+vhhnq3wk4/J0dP5p6R1CsR/S07Ju4/YMW4tjzhLKqdAsu9ZxAWi8vwPrFKeqWQ6",
	"sLIu/MBKHUvrs4wBhb6ch1aXjq7Tc7SxReN1D3BZ65d+cMO30yePr/28UzQKsA1FPyiBJwx9LzNZmRfj",
	"ZyJ2Llek+7b8UNhLS0tLrLpW/SsAAP//Ap93u1kkAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
